---
title: "1043a3"
author: "Zirui Liu"
date: "2022-10-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
getwd()
```
```{r}
t <- read.csv("C:/cygwin/home/zirui/timestamp.txt",header = FALSE)
```

```{r}
Da <- data.frame(strptime(t$V1, "%a %b %d %T %z %Y",tz="UTC"))
```
3) [6 marks] (R code) Once you’ve converted the timestamps, use the hist()
function to plot the data. [Hint: you may need to set the number of bins
sufficiently high to see the variation over time well.
```{r}
hist(
  Da$strptime.t.V1....a..b..d..T..z..Y...tz....UTC..,
  col = 'skyblue3',
  breaks =35,
  xlab ="time",
  freq=TRUE,
  main="Histogram on number of Tweets about Donald Trump",
  )
```


```{r}
help("hist")
```

```{r}
ac <- read.csv("C:/cygwin/home/zirui/author_count.txt",header = FALSE,sep=" ")
```



```{r}
hist(
  ac[[1]],
  col = 'skyblue3',
  breaks =50,
  xlab ="unique authors",
  freq=TRUE,
  main="Histogram o the distribution over number of tweets per author"
  )

```